name: crypto_keys_plus
description: A library for doing cryptographic signing/verifying and encrypting/decrypting.
version: 0.4.0
homepage: https://github.com/Bdaya-Dev/crypto_keys
funding:
 - https://github.com/sponsors/rbellens

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  pointycastle: ^3.6.2
  meta: ^1.3.0
  collection: ^1.14.13

dev_dependencies:
  test: ^1.16.2
  lints: ^2.0.0
  melos: ^3.1.1
